import { WebSocketProvider } from '../components/webSocketProvider/webSocketProvider';
import styles from './globals.module.css';
import Header from '../components/header/header';

export const metadata = {
  title: 'Reticketify',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className={styles.body}>
        <WebSocketProvider />
        <Header />
        <div  className={styles.content}>
          {children}
        </div>
      </body>
    </html>
  );
}
